blank_issues_enabled: false
contact_links:
  - name: First-time contributor?
    url: https://github.com/Souvik606/Google-sheets/blob/master/README.md
    about: Follow these instructions to get started.
  - name: Community Support
    url: https://github.com/Souvik606/Google-sheets/discussions
    about: Please ask and answer questions here.